# 阿美爸爸畫布 66 張高清原圖下載（hash 檔名，下載後阿地親眼看圖再改名）
$dir = "C:\Users\chenj\Documents\Claude\Projects\自動化每天更新FB 地藏 10輪經\阿美爸爸下載檔案\_raw"
New-Item -ItemType Directory -Path $dir -Force | Out-Null
$n=0
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/BAhyax52vzAE61Qi.png" -OutFile "$dir\BAhyax52vzAE61Qi.png" -UseBasicParsing; Write-Host "$n/66 BAhyax52vzAE61Qi OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/GZr6ZJQctpAqIBhb.png" -OutFile "$dir\GZr6ZJQctpAqIBhb.png" -UseBasicParsing; Write-Host "$n/66 GZr6ZJQctpAqIBhb OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/ffFwC0RO6U7P17fo.png" -OutFile "$dir\ffFwC0RO6U7P17fo.png" -UseBasicParsing; Write-Host "$n/66 ffFwC0RO6U7P17fo OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/HsPHVxKjgJDEH8c4.png" -OutFile "$dir\HsPHVxKjgJDEH8c4.png" -UseBasicParsing; Write-Host "$n/66 HsPHVxKjgJDEH8c4 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/tbo70obC5ZAtySxf.png" -OutFile "$dir\tbo70obC5ZAtySxf.png" -UseBasicParsing; Write-Host "$n/66 tbo70obC5ZAtySxf OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/qaTx3ilvgSCA4oXr.png" -OutFile "$dir\qaTx3ilvgSCA4oXr.png" -UseBasicParsing; Write-Host "$n/66 qaTx3ilvgSCA4oXr OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/Cw9jp7CP6G4TTi6H.png" -OutFile "$dir\Cw9jp7CP6G4TTi6H.png" -UseBasicParsing; Write-Host "$n/66 Cw9jp7CP6G4TTi6H OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/3W7QK4BDGv9tdDwq.png" -OutFile "$dir\3W7QK4BDGv9tdDwq.png" -UseBasicParsing; Write-Host "$n/66 3W7QK4BDGv9tdDwq OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/KWXb9rioAFDXl0lb.png" -OutFile "$dir\KWXb9rioAFDXl0lb.png" -UseBasicParsing; Write-Host "$n/66 KWXb9rioAFDXl0lb OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/oYOFJllbHHBcQj01.png" -OutFile "$dir\oYOFJllbHHBcQj01.png" -UseBasicParsing; Write-Host "$n/66 oYOFJllbHHBcQj01 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/CFlbc48MctFMpQnr.png" -OutFile "$dir\CFlbc48MctFMpQnr.png" -UseBasicParsing; Write-Host "$n/66 CFlbc48MctFMpQnr OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/x9yDXAvqOL2Hjf0C.png" -OutFile "$dir\x9yDXAvqOL2Hjf0C.png" -UseBasicParsing; Write-Host "$n/66 x9yDXAvqOL2Hjf0C OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/RHYrHVXaXUERuuSj.png" -OutFile "$dir\RHYrHVXaXUERuuSj.png" -UseBasicParsing; Write-Host "$n/66 RHYrHVXaXUERuuSj OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/mte8fvl2V7D8fRO1.png" -OutFile "$dir\mte8fvl2V7D8fRO1.png" -UseBasicParsing; Write-Host "$n/66 mte8fvl2V7D8fRO1 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/QiND9wTaYI9NwvIb.png" -OutFile "$dir\QiND9wTaYI9NwvIb.png" -UseBasicParsing; Write-Host "$n/66 QiND9wTaYI9NwvIb OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/56ZWLIyPsq8QToqf.png" -OutFile "$dir\56ZWLIyPsq8QToqf.png" -UseBasicParsing; Write-Host "$n/66 56ZWLIyPsq8QToqf OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/i25kP4Ce8QAIa9Jc.png" -OutFile "$dir\i25kP4Ce8QAIa9Jc.png" -UseBasicParsing; Write-Host "$n/66 i25kP4Ce8QAIa9Jc OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/2REIlj8JFEEyo0Fq.png" -OutFile "$dir\2REIlj8JFEEyo0Fq.png" -UseBasicParsing; Write-Host "$n/66 2REIlj8JFEEyo0Fq OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/V1quUGTuXGJEFIzx.png" -OutFile "$dir\V1quUGTuXGJEFIzx.png" -UseBasicParsing; Write-Host "$n/66 V1quUGTuXGJEFIzx OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/hFr1CvgvT9Aurutm.png" -OutFile "$dir\hFr1CvgvT9Aurutm.png" -UseBasicParsing; Write-Host "$n/66 hFr1CvgvT9Aurutm OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/vQWNygmBNp2ymDpT.png" -OutFile "$dir\vQWNygmBNp2ymDpT.png" -UseBasicParsing; Write-Host "$n/66 vQWNygmBNp2ymDpT OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/3NzpIVcBgM9TvU8b.png" -OutFile "$dir\3NzpIVcBgM9TvU8b.png" -UseBasicParsing; Write-Host "$n/66 3NzpIVcBgM9TvU8b OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/NKitfdITyJJFgw74.png" -OutFile "$dir\NKitfdITyJJFgw74.png" -UseBasicParsing; Write-Host "$n/66 NKitfdITyJJFgw74 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/Okr52vswgXGrNYTH.png" -OutFile "$dir\Okr52vswgXGrNYTH.png" -UseBasicParsing; Write-Host "$n/66 Okr52vswgXGrNYTH OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/W7uaCaIPyv7tsxXy.png" -OutFile "$dir\W7uaCaIPyv7tsxXy.png" -UseBasicParsing; Write-Host "$n/66 W7uaCaIPyv7tsxXy OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/0pKSwpBPZrGiY37T.png" -OutFile "$dir\0pKSwpBPZrGiY37T.png" -UseBasicParsing; Write-Host "$n/66 0pKSwpBPZrGiY37T OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/eq7HJzzwxXFCNopC.png" -OutFile "$dir\eq7HJzzwxXFCNopC.png" -UseBasicParsing; Write-Host "$n/66 eq7HJzzwxXFCNopC OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/PEat0c5Y7U37JOJ2.png" -OutFile "$dir\PEat0c5Y7U37JOJ2.png" -UseBasicParsing; Write-Host "$n/66 PEat0c5Y7U37JOJ2 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/grXZm8CXjJaB5Z6G.png" -OutFile "$dir\grXZm8CXjJaB5Z6G.png" -UseBasicParsing; Write-Host "$n/66 grXZm8CXjJaB5Z6G OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/xmAPOoJtWnDQzXq1.png" -OutFile "$dir\xmAPOoJtWnDQzXq1.png" -UseBasicParsing; Write-Host "$n/66 xmAPOoJtWnDQzXq1 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/4JHJumCACn9dviNj.png" -OutFile "$dir\4JHJumCACn9dviNj.png" -UseBasicParsing; Write-Host "$n/66 4JHJumCACn9dviNj OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/TaJXzlsTaD3hRTwY.png" -OutFile "$dir\TaJXzlsTaD3hRTwY.png" -UseBasicParsing; Write-Host "$n/66 TaJXzlsTaD3hRTwY OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/e2m0FsqLA6Kaotsr.png" -OutFile "$dir\e2m0FsqLA6Kaotsr.png" -UseBasicParsing; Write-Host "$n/66 e2m0FsqLA6Kaotsr OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/3TeAF29k4eHxW6op.png" -OutFile "$dir\3TeAF29k4eHxW6op.png" -UseBasicParsing; Write-Host "$n/66 3TeAF29k4eHxW6op OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/84ueofkCkCBOHSuO.png" -OutFile "$dir\84ueofkCkCBOHSuO.png" -UseBasicParsing; Write-Host "$n/66 84ueofkCkCBOHSuO OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/o8JGOwD3tX7kghjT.png" -OutFile "$dir\o8JGOwD3tX7kghjT.png" -UseBasicParsing; Write-Host "$n/66 o8JGOwD3tX7kghjT OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/e5VFs1taL3GiRGPy.png" -OutFile "$dir\e5VFs1taL3GiRGPy.png" -UseBasicParsing; Write-Host "$n/66 e5VFs1taL3GiRGPy OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/FFlL4bGCzv7SqfLV.png" -OutFile "$dir\FFlL4bGCzv7SqfLV.png" -UseBasicParsing; Write-Host "$n/66 FFlL4bGCzv7SqfLV OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/vwPiUla4Ej5AxYSp.png" -OutFile "$dir\vwPiUla4Ej5AxYSp.png" -UseBasicParsing; Write-Host "$n/66 vwPiUla4Ej5AxYSp OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/2RnSXH5eqOFwTWm5.png" -OutFile "$dir\2RnSXH5eqOFwTWm5.png" -UseBasicParsing; Write-Host "$n/66 2RnSXH5eqOFwTWm5 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/vSIAP26WELWtz9p9.png" -OutFile "$dir\vSIAP26WELWtz9p9.png" -UseBasicParsing; Write-Host "$n/66 vSIAP26WELWtz9p9 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/uD9QYTr9ES6tgGpC.png" -OutFile "$dir\uD9QYTr9ES6tgGpC.png" -UseBasicParsing; Write-Host "$n/66 uD9QYTr9ES6tgGpC OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/GVr0nnsudv7UQ2Wg.png" -OutFile "$dir\GVr0nnsudv7UQ2Wg.png" -UseBasicParsing; Write-Host "$n/66 GVr0nnsudv7UQ2Wg OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/eprqRQZKp820ubQq.png" -OutFile "$dir\eprqRQZKp820ubQq.png" -UseBasicParsing; Write-Host "$n/66 eprqRQZKp820ubQq OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/YCxVIv8w1I6jTNuk.png" -OutFile "$dir\YCxVIv8w1I6jTNuk.png" -UseBasicParsing; Write-Host "$n/66 YCxVIv8w1I6jTNuk OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/8U72AgLqS33kKLA1.png" -OutFile "$dir\8U72AgLqS33kKLA1.png" -UseBasicParsing; Write-Host "$n/66 8U72AgLqS33kKLA1 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/4fOYMfgsOn4FIIHW.png" -OutFile "$dir\4fOYMfgsOn4FIIHW.png" -UseBasicParsing; Write-Host "$n/66 4fOYMfgsOn4FIIHW OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/ghV7nBZO4D2bHoKz.png" -OutFile "$dir\ghV7nBZO4D2bHoKz.png" -UseBasicParsing; Write-Host "$n/66 ghV7nBZO4D2bHoKz OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/FkPgwiQPDt22T8LQ.png" -OutFile "$dir\FkPgwiQPDt22T8LQ.png" -UseBasicParsing; Write-Host "$n/66 FkPgwiQPDt22T8LQ OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/4fzJ2N4XxBJyJoNV.png" -OutFile "$dir\4fzJ2N4XxBJyJoNV.png" -UseBasicParsing; Write-Host "$n/66 4fzJ2N4XxBJyJoNV OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/o8eyZnQL7fGWzIxe.png" -OutFile "$dir\o8eyZnQL7fGWzIxe.png" -UseBasicParsing; Write-Host "$n/66 o8eyZnQL7fGWzIxe OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/0mJ3pWq2Nh8FBYsf.png" -OutFile "$dir\0mJ3pWq2Nh8FBYsf.png" -UseBasicParsing; Write-Host "$n/66 0mJ3pWq2Nh8FBYsf OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/TwHGM0PQeBER3E5w.png" -OutFile "$dir\TwHGM0PQeBER3E5w.png" -UseBasicParsing; Write-Host "$n/66 TwHGM0PQeBER3E5w OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/a0LpWoJYPx3OBHEJ.png" -OutFile "$dir\a0LpWoJYPx3OBHEJ.png" -UseBasicParsing; Write-Host "$n/66 a0LpWoJYPx3OBHEJ OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/uNdvsKK1SSENMe3i.png" -OutFile "$dir\uNdvsKK1SSENMe3i.png" -UseBasicParsing; Write-Host "$n/66 uNdvsKK1SSENMe3i OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/MyvJGV833nD8kFfW.png" -OutFile "$dir\MyvJGV833nD8kFfW.png" -UseBasicParsing; Write-Host "$n/66 MyvJGV833nD8kFfW OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/pBKneMApcbNwZq0e.png" -OutFile "$dir\pBKneMApcbNwZq0e.png" -UseBasicParsing; Write-Host "$n/66 pBKneMApcbNwZq0e OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/zFlYSJJgdQ51q61Q.png" -OutFile "$dir\zFlYSJJgdQ51q61Q.png" -UseBasicParsing; Write-Host "$n/66 zFlYSJJgdQ51q61Q OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/8gtuhmUCSALFNZoo.png" -OutFile "$dir\8gtuhmUCSALFNZoo.png" -UseBasicParsing; Write-Host "$n/66 8gtuhmUCSALFNZoo OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/5RuvebPix995fov5.png" -OutFile "$dir\5RuvebPix995fov5.png" -UseBasicParsing; Write-Host "$n/66 5RuvebPix995fov5 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/La4pQgHyLP1dkAOi.png" -OutFile "$dir\La4pQgHyLP1dkAOi.png" -UseBasicParsing; Write-Host "$n/66 La4pQgHyLP1dkAOi OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/6ufEBWOWNRCnV9I3.png" -OutFile "$dir\6ufEBWOWNRCnV9I3.png" -UseBasicParsing; Write-Host "$n/66 6ufEBWOWNRCnV9I3 OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/zb5Uk9EVYR10xJ3n.png" -OutFile "$dir\zb5Uk9EVYR10xJ3n.png" -UseBasicParsing; Write-Host "$n/66 zb5Uk9EVYR10xJ3n OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/20u4XKQPAPJwTJAc.png" -OutFile "$dir\20u4XKQPAPJwTJAc.png" -UseBasicParsing; Write-Host "$n/66 20u4XKQPAPJwTJAc OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/yc4gYu5Rdf69QXej.png" -OutFile "$dir\yc4gYu5Rdf69QXej.png" -UseBasicParsing; Write-Host "$n/66 yc4gYu5Rdf69QXej OK" -ForegroundColor Green
$n++; Invoke-WebRequest -Uri "https://a.lovart.ai/artifacts/agent/FiC9YFCUoB1DHofE.png" -OutFile "$dir\FiC9YFCUoB1DHofE.png" -UseBasicParsing; Write-Host "$n/66 FiC9YFCUoB1DHofE OK" -ForegroundColor Green
Write-Host "✅ 全部完成，共 $n 張，存在 $dir" -ForegroundColor Cyan
